package i18n

var cloud_sync_gateway_aliyunEN = map[string]string{
	"cmd.cloud_sync_gateway.create.aliyun.short":              "Create an Alibaba Cloud cloud sync gateway",
	"help.cloud_sync_gateway.create.aliyun":                   cloudSyncGatewayCreateAliyunEN,
	"cmd.target.cloud_sync_gateway.create.aliyun.usage_notes": "Use this command to create an Alibaba Cloud block-storage cloud-sync-gateway.\n\nParameter Sources:\n  --cloud-account-id string\n    Comes from `cloud-account create --cloud-type aliyun --storage-type block`, or from `cloud-account list` / `cloud-account detail`.\n\n  Other resource flags\n    Follow the observed operator order with these commands first:\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --fetch-res zones \\\n        --output json\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --fetch-res flavors \\\n        --output json\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --output json\n\n    If the selected VPC or subnet needs extra validation, then run:\n      hyperbdrctl target cloud-sync-gateway subnet-config --help\n\nThe minimum create command is:\n  hyperbdrctl cloud-sync-gateway create --cloud-type aliyun \\\n    --cloud-account-id <account_id> \\\n    --zone-id <zone_id> \\\n    --image-id <image_id> \\\n    --flavor-id <flavor_id> \\\n    --network-id <network_id> \\\n    --subnet-id <subnet_id> \\\n    --system-disk-type-id <system_disk_type_id>\n\nDefault behavior:\n  The saved cloud-account region is used automatically; do not pass `--region-id`.\n  When `--hd-control-network` is omitted, the CLI defaults it to `floating_ip_with_hg_proxy`; in floating-IP gateway modes, `--bandwidth-size` defaults to `100`.\n\nTo inspect the final request body first, add:\n  --preview-request\n\nAfter create returns a storage ID, continue with:\n  hyperbdrctl cloud-sync-gateway detail --id <storage_id>\n  hyperbdrctl cloud-sync-gateway wait --id <storage_id>",
	"cmd.block_storages.create.aliyun.short":                  "Create Alibaba Cloud block-storage gateway",
	"cmd.block_storages.create.aliyun.long":                   "Create the validated Alibaba Cloud HyperGate cloud-sync-gateway payload.\nThe CLI mirrors the observed resource, network, and transition-image flow before sending the final create request.",
	"cmd.block_storages.create.aliyun.quick_start":            "The minimum required input is:\n  --cloud-account-id",
	"cmd.block_storages.create.aliyun.automatic_behavior":     "- If `--region-id` is omitted, the CLI fills it from the saved\n  cloud-account metadata.\n- If `--zone-id`, `--image-id`, or `--system-disk-type-id` is omitted,\n  the CLI selects the validated default candidate from the\n  prerequisite lookups.\n- If `--flavor-id` is omitted, the CLI selects a validated flavor\n  candidate that meets the minimum gateway requirement of 2 vCPUs and\n  4 GiB RAM.\n- If `--network-id` or `--subnet-id` is omitted, the CLI selects the\n  first validated network and matching subnet candidate.\n- If `--boot-loader-image-id` is omitted, the CLI auto-selects the\n  first Windows transition-image candidate.\n- If `--hg-control-network` or `--hg-data-network` is omitted, the\n  CLI defaults both to `floating_ip_without_proxy`.\n- If `--hd-control-network` is omitted, the CLI defaults it to\n  `floating_ip_with_hg_proxy`; Alibaba Cloud then defaults\n  `--bandwidth-size` to `100` for floating-IP gateway modes.",
	"cmd.block_storages.create.aliyun.examples":               "# Minimal create\nhyperbdrctl cloud-sync-gateway create aliyun \\\n  --cloud-account-id <account_id>\n\n# Manual resource override\nhyperbdrctl cloud-sync-gateway create aliyun \\\n  --cloud-account-id <account_id> \\\n  --region-id cn-beijing \\\n  --zone-id cn-beijing-l \\\n  --flavor-id ecs.e-c1m2.large \\\n  --network-id <vpc_id> \\\n  --subnet-id <subnet_id> \\\n  --boot-loader-image-id <windows_image_id>",
	"cmd.block_storages.create.aliyun.notes":                  "- Validated flow for Alibaba Cloud block storage.\n- Queries `/hypermotion/v1/cloud_accounts/{id}/action` for the same\n  zone, flavor, image, system-disk, network, and subnet lookups used\n  by the observed UI flow.\n- Queries `/api/v3/getCloudInfo` for Windows transition images.",
	"cmd.block_storages.create.aliyun.workflow":               "1. Resolve zone candidates with\n   `target cloud-sync-gateway resources --fetch-res zones`.\n2. Resolve the flavor with\n   `target cloud-sync-gateway resources --fetch-res flavors`.\n3. Resolve image, system disk type, network, and subnet candidates\n   with `target cloud-sync-gateway resources`.\n4. Confirm subnet defaults with `target cloud-sync-gateway subnet-config` if the\n   selected VPC or subnet requires validation.\n5. Query Windows repair-image candidates with\n   `target cloud-sync-gateway resources --fetch-res win_hd_images` when you need the UI-equivalent\n   repair image.\n6. Submit `target cloud-sync-gateway create aliyun` with the resolved IDs.",
	"cmd.block_storages.create.aliyun.minimum_flags":          "--cloud-account-id",
	"cmd.block_storages.create.aliyun.common_optional_flags":  "--region-id\n--boot-loader-image-id\n--zone-id\n--flavor-id\n--image-id\n--network-id\n--subnet-id\n--system-disk-type-id\n--system-disk-size\n--hg-control-network\n--hg-data-network",
	"cmd.block_storages.create.aliyun.related":                "hyperbdrctl target cloud-sync-gateway resources \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --fetch-res zones \\\n  --output json\nhyperbdrctl target cloud-sync-gateway subnet-config \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --zone-id <zone_id> \\\n  --network-id <network_id>\nhyperbdrctl target cloud-sync-gateway resources \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --fetch-res win_hd_images \\\n  --output json",
	"cmd.block_storages.create.aliyun.next_steps":             "If the saved cloud-account metadata does not point to the target\nregion, pass `--region-id` explicitly or correct the cloud account\nfirst.",
}
