package i18n

var cloud_sync_gateway_openstackEN = map[string]string{
	"cmd.cloud_sync_gateway.create.openstack.short":              "Create an OpenStack cloud sync gateway",
	"help.cloud_sync_gateway.create.openstack":                   cloudSyncGatewayCreateOpenstackEN,
	"cmd.target.cloud_sync_gateway.create.openstack.usage_notes": "Use this command to create an OpenStack cloud-sync-gateway that matches the current block-storage extension wizard.\n\nThe real UI flow has two steps: create the cloud account first, then move directly into \"Set Cloud Sync Gateway\". In the CLI that maps to `cloud-account create --cloud-type openstack --storage-type block`, followed by this command.\n\nParameter Sources:\n  --cloud-account-id string\n    Comes from the result of `cloud-account create --cloud-type openstack --storage-type block`, or from `cloud-account list` / `cloud-account detail`.\n\n  --boot-loader-image-id string\n    Start by fetching the gateway creation resources in one response:\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --output json\n\n    Focus on these fields:\n      `cloud_info.boot_loader_images`\n      `cloud_info.images`\n      `cloud_info.compute_zones`\n      `cloud_info.flavors`\n      `cloud_info.networks`\n      `cloud_info.subnets`\n      `cloud_info.volume_types`\n      `cloud_info.auth_info.project_id`\n\n    To inspect only one resource group, add:\n      --fetch-res win_hd_images\n\n  Other optional resource flags:\n    `--project-id`, `--region-id`, `--compute-zone-id`, `--image-id`, `--flavor-id`, `--network-id`, `--subnet-id`, `--volume-type-id`, and `--boot-loader-flavor-id`\n    can be taken from the same `resources` response.\n\nThe minimum create command is:\n  hyperbdrctl cloud-sync-gateway create openstack \\\n    --cloud-account-id <account_id> \\\n    --boot-loader-image-id <windows_image_id>\n\nOpenStack does not use `subnet-config` as a stable prerequisite in the current backend. To inspect the final request body after the CLI applies the same defaults as the UI, run:\n  hyperbdrctl --output json target cloud-sync-gateway create openstack \\\n    --cloud-account-id <account_id> \\\n    --boot-loader-image-id <windows_image_id> \\\n    --preview-request\n\nThe validated defaults match the current UI:\n  `system-disk-size=50`, `block-store-zone-id=<compute_zone_id>`, `boot-types-id=boot_from_volume`, `hg-control-network=floating_ip_without_proxy`, and `hg-data-network=floating_ip_without_proxy`\n\nAfter create returns a storage ID, continue with:\n  hyperbdrctl cloud-sync-gateway detail --id <storage_id> --output json\n  hyperbdrctl cloud-sync-gateway wait --id <storage_id>",
	"cmd.block_storages.create.openstack.short":                  "Create OpenStack block-storage gateway",
	"cmd.block_storages.create.openstack.long":                   "Create the validated OpenStack HyperGate cloud-sync-gateway payload. When optional IDs are omitted, the CLI first queries account-scoped gateway resources and applies the same default candidates as the current UI.",
	"cmd.block_storages.create.openstack.examples":               "hyperbdrctl cloud-sync-gateway create openstack --cloud-account-id <account_id> --boot-loader-image-id <windows_image_id>\nhyperbdrctl cloud-sync-gateway create openstack --cloud-account-id <account_id> --project-id <project_id> --region-id RegionOne --compute-zone-id nova --image-id <linux_image_id> --flavor-id <flavor_id> --network-id <network_id> --boot-loader-image-id <windows_image_id> --boot-loader-flavor-id <flavor_id> --volume-type-id <volume_type_id>",
	"cmd.block_storages.create.openstack.notes":                  "- Validated flow for OpenStack block storage.\n- Start with `target cloud-sync-gateway resources --cloud-account-id <account_id> --output json` to confirm the key resource IDs in one response.\n- `--flavor-id` must resolve to a gateway flavor with at least 2 vCPUs and 4 GiB RAM.\n- Defaults match the observed UI: `boot_from_volume` and public-network gateway modes.",
	"cmd.block_storages.create.openstack.workflow":               "1. Confirm the cloud account and boot loader image.\n2. Query the account-scoped gateway resources and pin explicit IDs only when you need full control.\n3. Omit optional IDs only when the observed UI defaults are acceptable.\n4. Submit `target cloud-sync-gateway create openstack` and review the resolved metadata in JSON output if needed.",
	"cmd.block_storages.create.openstack.minimum_flags":          "--cloud-account-id\n--boot-loader-image-id",
	"cmd.block_storages.create.openstack.common_optional_flags":  "--project-id\n--region-id\n--compute-zone-id\n--image-id\n--flavor-id\n--network-id\n--subnet-id\n--volume-type-id\n--boot-loader-flavor-id\n--hg-control-network\n--hg-data-network",
	"cmd.block_storages.create.openstack.related":                "hyperbdrctl cloud-account detail --id <account_id>\nhyperbdrctl cloud-sync-gateway create --help",
	"cmd.block_storages.create.openstack.next_steps":             "Use `--output json` on the create command when you want to inspect the final resolved request result in scripts.",
}
