package i18n

var cloud_sync_gateway_aliyunZH = map[string]string{
	"cmd.cloud_sync_gateway.create.aliyun.short":              "创建阿里云云同步网关",
	"help.cloud_sync_gateway.create.aliyun":                   cloudSyncGatewayCreateAliyunZH,
	"cmd.target.cloud_sync_gateway.create.aliyun.usage_notes": "该命令用于创建阿里云块存储云同步网关。\n\n参数来源：\n  --cloud-account-id string\n    来自 `cloud-account create --cloud-type aliyun --storage-type block` 的返回结果，或 `cloud-account list` / `cloud-account detail`。\n\n  其它资源参数\n    可按真实顺序先执行下面这些命令：\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --fetch-res zones \\\n        --output json\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --fetch-res flavors \\\n        --output json\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --output json\n\n    如需校验所选 VPC / 子网的默认值，再执行：\n      hyperbdrctl target cloud-sync-gateway subnet-config --help\n\n最小创建命令如下：\n  hyperbdrctl cloud-sync-gateway create --cloud-type aliyun \\\n    --cloud-account-id <account_id> \\\n    --zone-id <zone_id> \\\n    --image-id <image_id> \\\n    --flavor-id <flavor_id> \\\n    --network-id <network_id> \\\n    --subnet-id <subnet_id> \\\n    --system-disk-type-id <system_disk_type_id>\n\n默认行为：\n  云账号中保存的区域会自动用于创建请求，无需传入 `--region-id`。\n  未显式传入 `--hd-control-network` 时，CLI 默认使用 `floating_ip_with_hg_proxy`；在浮动 IP 网关模式下，`--bandwidth-size` 默认取 `100`。\n\n如需先核对最终请求体，可附加：\n  --preview-request\n\n创建返回存储 ID 后，建议继续执行：\n  hyperbdrctl cloud-sync-gateway detail --id <storage_id>\n  hyperbdrctl cloud-sync-gateway wait --id <storage_id>",
	"cmd.block_storages.create.aliyun.short":                  "创建阿里云块存储云同步网关",
	"cmd.block_storages.create.aliyun.long":                   "创建已验证的阿里云 HyperGate 云同步网关请求。\nCLI 会按当前 UI 的资源、网络和过渡镜像流程先解析前置依赖，再提交最终创建请求。",
	"cmd.block_storages.create.aliyun.quick_start":            "最少只需要传入：\n  --cloud-account-id",
	"cmd.block_storages.create.aliyun.automatic_behavior":     "- 未传 `--region-id` 时，CLI 会从已保存的云账号元数据中\n  自动回填地域。\n- 未传 `--zone-id`、`--image-id` 或 `--system-disk-type-id` 时，\n  CLI 会从前置查询结果中自动选择已验证的默认候选值。\n- 未传 `--flavor-id` 时，CLI 会自动选择满足云同步网关最小要求\n  `2 vCPUs / 4 GiB RAM` 的已验证规格候选。\n- 未传 `--network-id` 或 `--subnet-id` 时，CLI 会自动选择\n  第一个已验证网络及其匹配的子网候选。\n- 未传 `--boot-loader-image-id` 时，CLI 会自动选择第一个\n  Windows 过渡镜像候选。\n- 未传 `--hg-control-network` 或 `--hg-data-network` 时，CLI\n  默认两者都使用 `floating_ip_without_proxy`。\n- 未传 `--hd-control-network` 时，CLI 默认使用\n  `floating_ip_with_hg_proxy`；在阿里云中，浮动 IP 网关模式下\n  `--bandwidth-size` 也会默认取 `100`。",
	"cmd.block_storages.create.aliyun.examples":               "# 最小创建\nhyperbdrctl cloud-sync-gateway create aliyun \\\n  --cloud-account-id <account_id>\n\n# 手动覆盖资源\nhyperbdrctl cloud-sync-gateway create aliyun \\\n  --cloud-account-id <account_id> \\\n  --region-id cn-beijing \\\n  --zone-id cn-beijing-l \\\n  --flavor-id ecs.e-c1m2.large \\\n  --network-id <vpc_id> \\\n  --subnet-id <subnet_id> \\\n  --boot-loader-image-id <windows_image_id>",
	"cmd.block_storages.create.aliyun.notes":                  "- 阿里云块存储已验证流程。\n- 会通过 `/hypermotion/v1/cloud_accounts/{id}/action` 查询与\n  页面一致的可用区、规格、镜像、系统盘、网络和子网候选。\n- 会通过 `/api/v3/getCloudInfo` 查询 Windows 过渡镜像。",
	"cmd.block_storages.create.aliyun.workflow":               "1. 使用\n   `target cloud-sync-gateway resources --fetch-res zones`\n   确认可用区候选。\n2. 使用\n   `target cloud-sync-gateway resources --fetch-res flavors`\n   确认规格。\n3. 使用 `target cloud-sync-gateway resources` 继续确认 image、system disk\n   type、network 和 subnet 等依赖资源。\n4. 如需校验所选 VPC / 子网的默认值，使用\n   `target cloud-sync-gateway subnet-config`。\n5. 如需 UI 同等的 Windows 修复镜像，使用\n   `target cloud-sync-gateway resources --fetch-res win_hd_images`。\n6. 带着最终确认的资源 ID 执行\n   `target cloud-sync-gateway create aliyun`。",
	"cmd.block_storages.create.aliyun.minimum_flags":          "--cloud-account-id",
	"cmd.block_storages.create.aliyun.common_optional_flags":  "--region-id\n--boot-loader-image-id\n--zone-id\n--flavor-id\n--image-id\n--network-id\n--subnet-id\n--system-disk-type-id\n--system-disk-size\n--hg-control-network\n--hg-data-network",
	"cmd.block_storages.create.aliyun.related":                "hyperbdrctl target cloud-sync-gateway resources \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --fetch-res zones \\\n  --output json\nhyperbdrctl target cloud-sync-gateway subnet-config \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --zone-id <zone_id> \\\n  --network-id <network_id>\nhyperbdrctl target cloud-sync-gateway resources \\\n  --cloud-account-id <account_id> \\\n  --region-id <region_id> \\\n  --fetch-res win_hd_images \\\n  --output json",
	"cmd.block_storages.create.aliyun.next_steps":             "如果云账号里保存的地域不是目标地域，请显式传入\n`--region-id`，或先修正云账号元数据。",
}
