package i18n

var cloud_sync_gateway_openstackZH = map[string]string{
	"cmd.cloud_sync_gateway.create.openstack.short":              "创建 OpenStack 云同步网关",
	"help.cloud_sync_gateway.create.openstack":                   cloudSyncGatewayCreateOpenstackZH,
	"cmd.target.cloud_sync_gateway.create.openstack.usage_notes": "该命令用于按当前 OpenStack 块存储扩展向导创建云同步网关。\n\n页面真实流程是两步：先创建云账号，再立即进入“设置云同步网关”。CLI 对应为先执行 `cloud-account create --cloud-type openstack --storage-type block`，再执行当前命令。\n\n参数来源：\n  --cloud-account-id string\n    来自 `cloud-account create --cloud-type openstack --storage-type block` 的返回结果，或 `cloud-account list` / `cloud-account detail`。\n\n  --boot-loader-image-id string\n    可先执行下面这条命令一次性获取网关创建所需资源：\n      hyperbdrctl target cloud-sync-gateway resources \\\n        --cloud-account-id <account_id> \\\n        --output json\n\n    重点关注：\n      `cloud_info.boot_loader_images`\n      `cloud_info.images`\n      `cloud_info.compute_zones`\n      `cloud_info.flavors`\n      `cloud_info.networks`\n      `cloud_info.subnets`\n      `cloud_info.volume_types`\n      `cloud_info.auth_info.project_id`\n\n    如需只查看某一类资源，再按需附加：\n      --fetch-res win_hd_images\n\n  其它可选资源参数：\n    `--project-id`、`--region-id`、`--compute-zone-id`、`--image-id`、`--flavor-id`、`--network-id`、`--subnet-id`、`--volume-type-id`、`--boot-loader-flavor-id`\n    均可从同一条 `resources` 响应中取得。\n\n最小创建命令如下：\n  hyperbdrctl cloud-sync-gateway create openstack \\\n    --cloud-account-id <account_id> \\\n    --boot-loader-image-id <windows_image_id>\n\nOpenStack 当前不走 `subnet-config` 作为稳定前置步骤；如需核对 CLI 按 UI 默认值自动补全后的最终请求体，应直接执行：\n  hyperbdrctl --output json target cloud-sync-gateway create openstack \\\n    --cloud-account-id <account_id> \\\n    --boot-loader-image-id <windows_image_id> \\\n    --preview-request\n\n当前已验证的默认行为与页面一致：\n  `system-disk-size=50`、`block-store-zone-id=<compute-zone-id>`、`boot-types-id=boot_from_volume`、`hg-control-network=floating_ip_without_proxy`、`hg-data-network=floating_ip_without_proxy`\n\n创建返回存储 ID 后，建议继续执行：\n  hyperbdrctl cloud-sync-gateway detail --id <storage_id> --output json\n  hyperbdrctl cloud-sync-gateway wait --id <storage_id>",
	"cmd.block_storages.create.openstack.short":                  "创建 OpenStack 块存储云同步网关",
	"cmd.block_storages.create.openstack.long":                   "创建已验证的 OpenStack HyperGate 云同步网关请求。未显式提供可选资源 ID 时，CLI 会先查询账号级网关资源，并按当前 UI 的默认候选项自动补全。",
	"cmd.block_storages.create.openstack.examples":               "hyperbdrctl cloud-sync-gateway create openstack --cloud-account-id <account_id> --boot-loader-image-id <windows_image_id>\nhyperbdrctl cloud-sync-gateway create openstack --cloud-account-id <account_id> --project-id <project_id> --region-id RegionOne --compute-zone-id nova --image-id <linux_image_id> --flavor-id <flavor_id> --network-id <network_id> --boot-loader-image-id <windows_image_id> --boot-loader-flavor-id <flavor_id> --volume-type-id <volume_type_id>",
	"cmd.block_storages.create.openstack.notes":                  "- OpenStack 块存储已验证流程。\n- 建议先执行 `target cloud-sync-gateway resources --cloud-account-id <account_id> --output json` 一次性确认关键资源。\n- `--flavor-id` 必须解析到至少 `2 vCPUs / 4 GiB RAM` 的网关规格。\n- 默认值与当前 UI 观察结果一致：`boot_from_volume`、公网网关网络方式。",
	"cmd.block_storages.create.openstack.workflow":               "1. 先确认云账号与 boot loader 镜像。\n2. 先查询账号级网关资源；如果你希望完全控制 project、region、flavor、network 等资源选择，再显式传入对应 ID。\n3. 只有在接受 UI 默认推荐资源时，才省略可选 ID。\n4. 执行 `target cloud-sync-gateway create openstack`，必要时配合 `--output json` 检查最终解析结果。",
	"cmd.block_storages.create.openstack.minimum_flags":          "--cloud-account-id\n--boot-loader-image-id",
	"cmd.block_storages.create.openstack.common_optional_flags":  "--project-id\n--region-id\n--compute-zone-id\n--image-id\n--flavor-id\n--network-id\n--subnet-id\n--volume-type-id\n--boot-loader-flavor-id\n--hg-control-network\n--hg-data-network",
	"cmd.block_storages.create.openstack.related":                "hyperbdrctl cloud-account detail --id <account_id>\nhyperbdrctl cloud-sync-gateway create --help",
	"cmd.block_storages.create.openstack.next_steps":             "如果你需要脚本化检查最终创建结果，建议在执行创建时配合 `--output json`。",
}
