package i18n

var cloud_resource_openstackEN = map[string]string{
	"cmd.cloud_resource.fetch.openstack.usage_notes":     "Use this command to fetch OpenStack read-only resources.\n\nParameter sources:\n  --auth-url string\n    In the platform UI, click the username in the top-right corner, open OpenStack RC file, and read OS_AUTH_URL.\n\n  --username string\n    Usually use the username shown in the top-right corner of the platform UI.\n\n  --password string\n    Enter the login password for that username.\n\n  --user-domain-id string\n    On the OpenStack control node, run `openstack user show <username>` and read `domain_id`; the default is usually `default`.\n\nRun the minimum query like this:\n  hyperbdrctl cloud-resource fetch --cloud-type %s --storage-type %s \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\nAdd `--region-id`, `--project-id`, `--project-domain-id`, `--project-name`, `--compute-zone-id`, or `--block-store-zone-id` only when continuing a selected context.",
	"help.cloud_resource.fetch.openstack.block":          cloudResourceFetchOpenstackBlockEN,
	"help.cloud_resource.fetch.openstack.object":         cloudResourceFetchOpenstackObjectEN,
	"help.cloud_resource.fetch.account.openstack.block":  cloudResourceFetchAccountOpenStackBlockEN,
	"help.cloud_resource.fetch.account.openstack.object": cloudResourceFetchAccountOpenStackObjectEN,
	"cmd.target.resource.block.openstack.usage_line":     "hyperbdrctl target resource block openstack [flags]",
	"cmd.target.resource.block.openstack.examples":       "hyperbdrctl target resource block openstack --auth-url http://openstack.example.invalid:5000/v3 --username autotest --password <password> --user-domain-id default --output json\nhyperbdrctl target resource block openstack --auth-url http://openstack.example.invalid:5000/v3 --username autotest --password <password> --user-domain-id default --fetch-res regions,projects --output json",
	"cmd.target.resource.block.openstack.usage_notes":    "Use this command to fetch OpenStack block resources directly from credentials.\n\nThis command does not require or accept `--cloud-account-id`.\n\nParameter sources:\n  --auth-url string\n    In the platform UI, click the username in the top-right corner, open OpenStack RC file, and read OS_AUTH_URL.\n\n  --username string\n    Usually use the username shown in the top-right corner of the platform UI.\n\n  --password string\n    Enter the login password for that username.\n\n  --user-domain-id string\n    On the OpenStack control node, run `openstack user show <username>` and read `domain_id`; the default is usually `default`.\n\nRun the minimum query like this:\n  hyperbdrctl target resource block openstack \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\n`--fetch-res` is optional. When omitted, the CLI auto-detects the returned resource sections and renders them in order.\n\nWhen you need to continue the query with selected context, add:\n  --region-id / --zone-id / --project-id / --project-domain-id / --project-name / --compute-zone-id / --block-store-zone-id",
	"cmd.target.resource.oss.openstack.usage_line":       "hyperbdrctl target resource oss openstack [flags]",
	"cmd.target.resource.oss.openstack.examples":         "hyperbdrctl target resource oss openstack --auth-url http://openstack.example.invalid:5000/v3 --username autotest --password <password> --user-domain-id default --output json\nhyperbdrctl target resource oss openstack --auth-url http://openstack.example.invalid:5000/v3 --username autotest --password <password> --user-domain-id default --fetch-res regions,projects --output json",
	"cmd.target.resource.oss.openstack.usage_notes":      "Use this command to fetch OpenStack object resources directly from credentials.\n\nThis command does not require or accept `--cloud-account-id`.\n\nParameter sources:\n  --auth-url string\n    In the platform UI, click the username in the top-right corner, open OpenStack RC file, and read OS_AUTH_URL.\n\n  --username string\n    Usually use the username shown in the top-right corner of the platform UI.\n\n  --password string\n    Enter the login password for that username.\n\n  --user-domain-id string\n    On the OpenStack control node, run `openstack user show <username>` and read `domain_id`; the default is usually `default`.\n\nRun the minimum query like this:\n  hyperbdrctl target resource oss openstack \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\n`--fetch-res` is optional. When omitted, the CLI auto-detects the returned resource sections and renders them in order.\n\nWhen you need to continue the query with selected context, add:\n  --region-id / --zone-id / --project-id / --project-domain-id / --project-name / --compute-zone-id / --block-store-zone-id",
}
