package i18n

var cloud_resource_openstackZH = map[string]string{
	"cmd.cloud_resource.fetch.openstack.usage_notes":     "该命令用于获取 OpenStack 只读资源。\n\n参数来源：\n  --auth-url string\n    登录平台后，点击右上角用户名，再点击【OpenStack RC 文件】，读取 OS_AUTH_URL。\n\n  --username string\n    通常使用平台右上角显示的用户名。\n\n  --password string\n    填写该用户名对应的登录密码。\n\n  --user-domain-id string\n    在 OpenStack 控制节点执行 `openstack user show <用户名>`，读取 `domain_id`；默认通常为 `default`。\n\n最小查询命令如下：\n  hyperbdrctl cloud-resource fetch --cloud-type %s --storage-type %s \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\n只有在继续带入已选上下文时，才附加 `--region-id`、`--project-id`、`--project-domain-id`、`--project-name`、`--compute-zone-id` 或 `--block-store-zone-id`。",
	"help.cloud_resource.fetch.openstack.block":          cloudResourceFetchOpenstackBlockZH,
	"help.cloud_resource.fetch.openstack.object":         cloudResourceFetchOpenstackObjectZH,
	"help.cloud_resource.fetch.account.openstack.block":  cloudResourceFetchAccountOpenStackBlockZH,
	"help.cloud_resource.fetch.account.openstack.object": cloudResourceFetchAccountOpenStackObjectZH,
	"cmd.target.resource.block.openstack.usage_line":     "hyperbdrctl target resource block openstack [参数]",
	"cmd.target.resource.block.openstack.examples":       "hyperbdrctl target resource block openstack --auth-url http://192.168.10.201:5000/v3 --username autotest --password <password> --user-domain-id default --output json\nhyperbdrctl target resource block openstack --auth-url http://192.168.10.201:5000/v3 --username autotest --password <password> --user-domain-id default --fetch-res regions,projects --output json",
	"cmd.target.resource.block.openstack.usage_notes":    "该命令用于直接通过凭证获取 OpenStack 块存储云资源。\n\n该命令既不需要也不接受 `--cloud-account-id`。\n\n参数来源：\n  --auth-url string\n    登录平台后，点击右上角用户名，再点击【OpenStack RC 文件】，读取 OS_AUTH_URL。\n\n  --username string\n    通常使用平台右上角显示的用户名。\n\n  --password string\n    填写该用户名对应的登录密码。\n\n  --user-domain-id string\n    在 OpenStack 控制节点执行 `openstack user show <用户名>`，读取 `domain_id`；默认通常为 `default`。\n\n最小查询命令如下：\n  hyperbdrctl target resource block openstack \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\n`--fetch-res` 可省略；省略时 CLI 会按后端实际返回的资源自动分段展示。\n\n如需把已选上下文继续带回后端，可按需补充：\n  --region-id / --zone-id / --project-id / --project-domain-id / --project-name / --compute-zone-id / --block-store-zone-id",
	"cmd.target.resource.oss.openstack.usage_line":       "hyperbdrctl target resource oss openstack [参数]",
	"cmd.target.resource.oss.openstack.examples":         "hyperbdrctl target resource oss openstack --auth-url http://192.168.10.201:5000/v3 --username autotest --password <password> --user-domain-id default --output json\nhyperbdrctl target resource oss openstack --auth-url http://192.168.10.201:5000/v3 --username autotest --password <password> --user-domain-id default --fetch-res regions,projects --output json",
	"cmd.target.resource.oss.openstack.usage_notes":      "该命令用于直接通过凭证获取 OpenStack 对象存储云资源。\n\n该命令既不需要也不接受 `--cloud-account-id`。\n\n参数来源：\n  --auth-url string\n    登录平台后，点击右上角用户名，再点击【OpenStack RC 文件】，读取 OS_AUTH_URL。\n\n  --username string\n    通常使用平台右上角显示的用户名。\n\n  --password string\n    填写该用户名对应的登录密码。\n\n  --user-domain-id string\n    在 OpenStack 控制节点执行 `openstack user show <用户名>`，读取 `domain_id`；默认通常为 `default`。\n\n最小查询命令如下：\n  hyperbdrctl target resource oss openstack \\\n    --auth-url <auth_url> \\\n    --username <username> \\\n    --password <password> \\\n    --user-domain-id <user_domain_id> \\\n    --output json\n\n`--fetch-res` 可省略；省略时 CLI 会按后端实际返回的资源自动分段展示。\n\n如需把已选上下文继续带回后端，可按需补充：\n  --region-id / --zone-id / --project-id / --project-domain-id / --project-name / --compute-zone-id / --block-store-zone-id",
}
